### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by BioDebojyoti** [BIMSBbioinfo/maui#10]
Hi @jonathanronen ,

Tried to install maui with pip, it didn't produce any errors. However, when I try importing maui and maui.tools it fails. Any help is appreciated.

(py3.6) pcddas@beagle:~/SOFTWARES$ python 
Python 3.6.0 | packaged by conda-forge | (default, Feb  9 2017, 14:36:55) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import maui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pcddas/miniconda2/envs/py3.6/lib/python3.6/site-packages/maui/__init__.py", line 1, in <module>
    from .model import Maui
  File "/home/pcddas/miniconda2/envs/py3.6/lib/python3.6/site-packages/maui/model.py", line 8, in <module>
    from .autoencoders_architectures import stacked_vae, deep_vae, train_model
  File "/home/pcddas/miniconda2/envs/py3.6/lib/python3.6/site-packages/maui/autoencoders_architectures.py", line 7, in <module>
    from keras.models import Model
  File "/home/pcddas/miniconda2/envs/py3.6/lib/python3.6/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/home/pcddas/miniconda2/envs/py3.6/lib/python3.6/site-packages/keras/models.py", line 19, in <module>
    from keras import backend
  File "/home/pcddas/miniconda2/envs/py3.6/lib/python3.6/site-packages/keras/backend.py", line 36, in <module>
    from tensorflow.python.eager.context import get_config
ImportError: cannot import name 'get_config'
>>>

**Comment by jonathanronen** [comment]
Hi there. The current version of maui is a bit picky about versions of the dependencies. You'll need to use Python 3.6 and TensorFlow 1 (not 2). E.g. `!pip install maui-tools matplotlib lifelines seaborn Keras==2.2.4 scikit-learn==0.20.0` should work.

An update so that maui will work with newer versions of these dependencies is coming as soon as I find the time :-)

Let me know if you're still running into trouble!
